### ISSUE TITLE
Simplify reducer registration

### ISSUE THREAD

**Issue by GregOnNet** [co-IT/ngrx-ducks#52]
Currently, the reducer generated by NgRx Ducks has to be added manually either to the StoreModule or an ActionReducerMap<T>.

The developer needs to maintain multiple files in order to set everything up.

It would be nice to allow `@StoreFacade` registering the reducer automatically.

## Draft

```ts
interface SliceA {
  entities: Dictionary<A>;
}

interface MyState {
  sliceA: SliceA
}

@StoreFacade<MyState>({ 
  feature: 'featureName',
  slice: 'sliceA',
  defaults: initialState 
})
export class MyFacade {}
```

## ToDos

- [x] Implement `StoreRegistrator`, registering a Reducer at Runtime
- [x] Allow Registering a reducer function
      @StoreFacade<MyState>({ registerInStore: ['featureName', initialState] })
- [x] Allow Registering a reducer map 
      @StoreFacade<MyState>({ registerInStore: ['featureName', 'sliceA', initialState] })
- [x] Provide StoreDuckModule overriding ReducerManager
- [x] Support Registration for `createMutableDuck`
- [x] Support Registration in `root`-Store

## Resources

- https://ngrx.io/guide/store/recipes/injecting
- https://github.com/ngrx/platform/blob/master/modules/store/src/reducer_manager.ts#L23

## Other information

Reducers are managed inside a BehaviourSubject (see Reducer_Manger & State<T>):
https://github.com/ngrx/platform/blob/ce96bb042916f057b70841a194fb6e7b851e1537/modules/store/src/state.ts#L26

It is possible to override the existing ReducerManager ([StackBlitz](https://stackblitz.com/edit/ngrx-slice-sniffer?file=src%2Fapp%2Freducer-manager-ext.ts)).

**Comment by GregOnNet** [comment]
Open PR in NgRx.
If this gets merged, it is easier for NgRx Ducks to access reducers registered in the Store https://github.com/ngrx/platform/pull/3064

**Comment by GregOnNet** [comment]
I am happy to announce that this issue can be closed 🎉 , since the feature has landed in the latest Release.
You can check out the result at https://stackblitz.com/edit/ngrx-ducks-12-9ztnzp?file=src/app/counter/store/counter/counter.facade.ts.

Happy Coding
Gregor
